-- CREATE TABLE sandwiches (
--   id int NOT NULL AUTO_INCREMENT,
--   price DECIMAL,
--   name VARCHAR(255),
--   description VARCHAR(255),
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE users (
--   id VARCHAR(255) NOT NULL,
--   name VARCHAR(255) NOT NULL,
--   email VARCHAR(255) NOT NULL,
--   password VARCHAR(255) NOT NULL,
--   PRIMARY KEY(id),
--   UNIQUE KEY email(email)
-- );

-- CREATE TABLE Salads (
--     id int NOT NULL AUTO_INCREMENT,
--     price DECIMAL,
--     name VARCHAR(255),
--     description VARCHAR(255),
--     PRIMARY KEY (id)
-- );